### ISSUE TITLE
Help to configure the ideal work environment

### ISSUE THREAD

**Issue by alessandro-satanassi** [TeamOpenFIRE/OpenFIRE-App#11]
I don't know if this is the right place to write, but I ask.
I would like to collaborate on the project. I know little about Qt, but this is not a problem. I ask which work environment (IDE) you use for the project, i.e. if QT Creator or VS code or something else. Let's say some help to get started and go less crazy to configure the ideal work environment. I use windows.

**Comment by SeongGino** [comment]
There are tools for integrating Qt inside of Visual Studio, though Qt's development environment is cross-platform. Use whichever works for you.
