### ISSUE TITLE
OpenFIREapp QT6 package for win64

### ISSUE THREAD

**Issue by alessandro-satanassi** [TeamOpenFIRE/OpenFIRE-App#12]
I managed to compile it without any problems using QT6 (6.7.2) without making any changes (on windows). If QT6 is ready for Linux too, I suggest putting the QT6 package on GitHub. I can send you the package if you want
the package comes a little bigger, but only by a little
Win64-QT6
[Uploading OpenFIREapp-qt6.zip…]()

**Comment by SeongGino** [comment]
There is no reason to have a Qt6 package for Windows as all it does is removes compatibility for Windows 7/8 users, which some people are still using for their builds (for whatever reason, is beyond me).

Good for you if you want to use Qt6, but there's no difference and all it will add is potential headache.
