### ISSUE TITLE
[BUG] Calibration curser overscan

### ISSUE THREAD

**Issue by jacobcapper** [TeamOpenFIRE/OpenFIRE-App#19]
**Describe the bug**
Mouse curser overscans bottom and right of screen on windows 10. 

**To Reproduce**
1. Go to Saved profiles 
2. Click on calibrate profile 1
3. Shoot centre and top curser.
4. curser shoots off the bottom of the screen.
5. Attempt to shoot where it should be
6. curser moves to the left
7. shoot curser
8. curser shoots off the right side of the screen.

**Expected behavior**
How do you think this should've behaved instead?
The curser should be at the bottom of the screen, not off it. 

**System Info**
 - OS: windows 22h2 build 19045.4780
 - Microcontroller board: Raspberry Pi Pico Board RP2040 https://vi.aliexpress.com/item/1005003371056277.html Color: Purple 16M
 - OpenFIRE Firmware version: OpenFIRE Public Release 5.2 - Dawn
 - OpenFIRE App version: OpenFIRE App Public Release 2.2 - Tsuzura

**Additional context**
Anything else we should know about this problem?
IR camera is set up with the dot at the top, led to the right and cable to the left. 
When viewing the ir test, all 4 leds are visible and camera motion is as expected. Tilt/move gun up, it tracks up. Tilt gun left, tracks left, etc.

**Comment by SeongGino** [comment]
Not an app problem, Cali is part of the firmware.

You can blame this on Windows, as it works fine on Linux.
