### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by MRTNSLS** [TeamOpenFIRE/OpenFIRE-App#21]
###### pls, kthx xoxo - Seong
___

**Describe the bug**
Small typo in README in required packages for building on Linux.
I think it should be libqt5serialport5-dev libqt5svg5-dev (instead of libqt5serialport-dev libqt5svg-dev)

**To Reproduce**
apt get install fails with unknown  package for libqt5serialport-dev and libqt5svg-dev

**Expected behavior**
The package to exist.

**System Info**
Raspberry pi 5 running Ubuntu 24

**Additional context**
(this is my first time submitting a bug on github, I'm sorry if this is too minor of an issue and if it should have been handled differently)

**Comment by SeongGino** [comment]
Also, **please** fill out the title properly next time.
