### ISSUE TITLE
[BUG] Waveshare RP2040 diagram error

### ISSUE THREAD

**Issue by Arakon** [TeamOpenFIRE/OpenFIRE-App#23]
___

**Describe the bug**
On the diagram of this board inside the app, pin 15 is shown twice. 

**To Reproduce**
Set the board type to Waveshare RP2040 Zero and check the bottom left area.
![image](https://github.com/user-attachments/assets/0525f818-af10-412b-a7d9-60c07ee3e8cc)

**Expected behavior**
Bottom row pin 15 should be labeled 13.

**System Info**
 - OS: Win11
 - Microcontroller board: waveshareZero
 - OpenFIRE Firmware version: 5.2
 - OpenFIRE App version: v2.2

**Additional context**
Anything else we should know about this problem?

**Comment by SeongGino** [comment]
That's just the SVG that was available. Not our bug, plus it's a pretty minimal thing since the real pin number is notated in the actual interface.

You're free to submit a fixed vector.
