### ISSUE TITLE
[BUG]  waveshare RP2040 board layout screen 

### ISSUE THREAD

**Issue by supernono-fr** [TeamOpenFIRE/OpenFIRE-App#30]
###### pls, kthx xoxo - Seong
___

**Describe the bug**
What exactly is the problem? Be concise, please!

**To Reproduce**
Steps to reproduce the behavior: (as an example)

**Expected behavior**
How do you think this should've behaved instead?

**System Info**
 - OS: [e.g. Windows (version), or Linux (distro + date/version)]
 - Microcontroller board: [e.g. `rpipico`]
 - OpenFIRE Firmware version: [e.g. v5.0-rc2]
 - OpenFIRE App version: [e.g. v2.0-rc2]

**Additional context**
Anything else we should know about this problem?

**Comment by SeongGino** [comment]
Didn't even touch the issue template. Not valid.
