### ISSUE TITLE
[BUG] Wrong picture in app

### ISSUE THREAD

**Issue by supernono-fr** [TeamOpenFIRE/OpenFIRE-App#31]
###### pls, kthx xoxo - Seong
___

**Describe the bug**
Hello, not realy a bug, but on the board layout screen the waveshare RP2040 picture have two pin 15, one between 12 & 14 and one between 14 & 26

**To Reproduce**
1- Connect Waveshare RP 2040 zero board
2- Launch OpenFIRE-App
3- Select com port
4- look at the picture of the board (bottom left) on the "Board Layout"  page

**Expected behavior**
How do you think this should've behaved instead?
Show the good picture

**System Info**
 - OS: [e.g. Windows 10
 - Microcontroller board: Waveshare RP2040 zero
 - OpenFIRE Firmware version: OpenFIRE App - Tsuzura [v2.2]
 - OpenFIRE App version: 5.2 "Dawn"

**Additional context**
Anything else we should know about this problem?
nothing else

**Comment by SeongGino** [comment]
For future reference, the disclaimer is meant for you to remove before submitting. Please read the submission instructions closely next time. The title also isn't descriptive enough.

As for the 'issue', the board SVGs like for the Waveshare are not made by us, and it shouldn't matter as the pin labeling/boxes show the right labeling anyways. Not our issue, but feel free to submit a fix if you feel so strongly about it.
